#include <iostream>
#include <cstdlib>
#include <ctime>

using namespace std;

int main()
{
	int num; // holding a random number generated by computer
	int guess; // holds the guess of the user
	bool isGuessed; // true if user guessed the number correctly
	int tries = 0; //holds the number of tries
	double diff;
	srand(time(0)); // initialize randomness with time
	num = rand() % 100; // ensure the number is 0 to 100

	isGuessed = false;
	cout << num << endl;
	cout << "I have a number between 0 and 100. Try to guess what it is." << endl << endl;


	while (!isGuessed)
	{
		cout << "So, what is your guess? ";
		cin >> guess;
		tries++;
		diff = guess - num;
		// testing cout << "Diff: " << diff << endl; 
		if (guess == num)
		{
			cout << "Phew... You got it in " << tries << " tries!" << endl << endl;
			isGuessed = true;
		}
		/*else if (guess < num)
		{
		cout << "Your guess is too low, go higher!" << endl << endl;
		}
		else if (guess > num)
		{
		cout << "Your guess is too high, go lower!" << endl << endl;
		}*/

		if (tries == 6) {
			cout << "You lost the game!" << endl;
			break;
		}

		// difference if statements
		if (diff == 0)
		{
			cout << "You found the number! " << endl;
		}
		else if (diff >= 50)
		{
			cout << "Way too High" << endl;
		}
		else if (diff >= 20)
		{
			cout << "You guess is high" << endl;
		}
		else if (diff >= 10)
		{
			cout << "Getting there but still high" << endl;
		}
		else if (diff >= 0)
		{
			cout << "Almost there but still high" << endl;
		}
		else if (diff <= -50)
		{
			cout << "Way too low" << endl;
		}
		else if (diff <= -20)
		{
			cout << "You guess is low!" << endl;
		}
		else if (diff <= -10)
		{
			cout << "Getting there but still low!" << endl;
		}
		else if (diff <= 0)
		{
			cout << "Getting there but still low!" << endl;
		}

	}

	system("PAUSE");
	return 0;
}